f1 = open("movie.txt")
title = f1.readline()
fee = f1.readline()
f1. close()
print ("안녕하세요? 관람 가능하신 영화와 요금은 다음과 같습니다.")
print ("영화 제목:", title)
print ("티켓 요금:", fee)
name = input("예약하실 분의 이름을 입력해 주세요.")
date = input("예약을 원하시는 날짜와 시간을 입력해 주세요:")

num = input("영화를 관람하실 인원을 입력해 주세요:")
total = fee
f2 = ("reserve.txt", "a")
print ("지불하실 금액은", total,"원 입니다.")
f2.write ("예약하신 분:"+name+"\n")
f2.write ("예약 일:"+date+"\n")
f2.write ("예약 인원:"+num+"명\n")
f2.write ("지불 금액:"+str(total)+"원\n")
f2.close()


f1 = open("movie.txt","w")
name= input("예약하실 분의 이름을 입력해주세요:")
people= input("영화를 관람하실 인원을 입력해주세요")
f1.write("예약하신 분:"+name+"\n")
f1.write("예약 인원:"+people)
f1.close()
f1 = open("movie.txt","r")
name=f1.readline()
peole=f1.readline()
print("예약한사람",name)
print("관람할 인원:",peole)
f1.close()

